name: Print Software Versions

on:
  push:
    branches: [ "laboratory-work-4" ]
  workflow_dispatch:

jobs:
  software_versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print .NET version
        run: dotnet --version

      - name: Print PostgreSQL version
        run: psql --version || echo "PostgreSQL client not installed"


