name: Print Software Versions

on:
  push:
    branches: [ main, laboratory-work-4, laboratory-work-4-v2 ]
  pull_request:
    branches: [ main ]

jobs:
  check-application-layer-software:
    runs-on: ubuntu-latest
    steps:
      - name: Check .NET version
        run: dotnet --version

      - name: Check C# compiler
        run: csc -version

  check-database-layer-software:
    runs-on: ubuntu-latest
    needs: check-application-layer-software
    steps:
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Check PostgreSQL version
        run: psql --version


