name: Print Software Versions

on:
  push:
    branches: [ laboratory-work-4-v2 ]
  pull_request:
    branches: [ laboratory-work-4-v2 ]

jobs:
  check-application-layer-software:
    runs-on: ubuntu-latest
    steps:
      - name: Check .NET version
        run: dotnet --version

      - name: Check .NET SDK info
        run: dotnet --info

  check-database-layer-software:
    runs-on: ubuntu-latest
    needs: check-application-layer-software
    steps:
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
      - name: Check PostgreSQL client version
        run: psql --version


