name: CSharp Code Convention

on:
  push:
    branches: [ main, laboratory-work-4, laboratory-work-4-v2 ]
  pull_request:
    branches: [ main ]

jobs:
  check-csharp-code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run DotNet format
        run: |
          dotnet tool install -g dotnet-format
          dotnet-format --verify-no-changes


