name: Program Code Convention

on:
  push:
    branches: [ "laboratory-work-4-v2" ]
  workflow_dispatch:

jobs:
  check_program_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check C# naming style
        run: |
          if grep -q "namespace" src/ProgramCode.cs; then
            echo "Code formatting OK"
          else
            echo "Convention fail"
            exit 1
          fi
